language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_install:
  - curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -
  - sudo bash -c "echo deb http://apt.basho.com $(lsb_release -sc) main > /etc/apt/sources.list.d/basho.list"
  - sudo apt-get update
  - sudo apt-get install -qq valgrind
  - sudo apt-get install -qq libevent-dev
  - sudo apt-get install -qq protobuf-compiler
  - sudo apt-get install -qq protobuf-c-compiler
  - sudo apt-get install -qq libprotobuf-dev
  - sudo apt-get install -qq libprotoc-dev
  - sudo apt-get install -qq libcunit1
  - sudo apt-get install -qq libcunit1-ncurses-dev
  - "yes n | sudo apt-get install riak"
  - ulimit -n 4096
  - sudo service riak start
  - wget https://protobuf-c.googlecode.com/files/protobuf-c-0.15.tar.gz
  - tar xvzf protobuf-c-0.15.tar.gz
  - cd protobuf-c-0.15
  - "./configure && make && sudo make install"
  - cd ..
before_script:
  - ./script/build_module.sh
  - search-cmd install testsearch
script:
  - PHP=`which php`
  - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=$PHP $PHP run-tests.php -q -m --show-diff
  - find . -name *.mem | xargs cat
